import Hopper.Accounts
import Hopper.Data.Checked
import Hopper.Data.Activities
import Hopper.Data.PencilSums

/-!
# The certificate

What `src/content/accounts.json` publishes about money, recomputed from its own
rows and proved. The statements are stable: they compare the reader's rows with
the reader's published figures, so they hold or fail as batches land without
this file changing. The data files beside it are generated by
`scripts/lean.mjs`; this one is not.

Nothing here certifies a reading. Whether « 16.66 » is what the leaf says is a
question for the photograph; what is certified is that, given what the
transcription says, the arithmetic the edition prints follows.
-/

namespace Hopper.Certificate
open Hopper

/-! ## 1. The three buckets -/

/-- The work books: the row count, the reader's rounding of every net, the
years recomputed from the rows, the running balance, and the totals as the sums
of the years. -/
theorem art_certified : artCertified Data.Art.rows Data.Art.published = true := by
  decide +kernel

theorem illustration_certified :
    bookCertified Data.Illustration.charges Data.Illustration.receipts
      Data.Illustration.published = true := by
  decide +kernel

theorem cashbook_certified :
    bookCertified Data.CashBook.charges Data.CashBook.receipts
      Data.CashBook.published = true := by
  decide +kernel

theorem art_totals_are_row_sums :
    Data.Art.published.totals.toBucket = Bucket.sum (artBuckets Data.Art.rows) := by
  decide +kernel

theorem illustration_totals_are_row_sums :
    Data.Illustration.published.totals.toBucket =
      Bucket.sum (bookBuckets Data.Illustration.charges Data.Illustration.receipts) := by
  decide +kernel

theorem cashbook_totals_are_row_sums :
    Data.CashBook.published.totals.toBucket =
      Bucket.sum (bookBuckets Data.CashBook.charges Data.CashBook.receipts) := by
  decide +kernel

/-- `accrued = collected + outstanding + notRecorded` for the work books'
totals — not by inspecting the four figures, but because they are the sum of
rows each of which satisfies it. -/
theorem art_totals_hold : Data.Art.published.totals.toBucket.Holds := by
  rw [art_totals_are_row_sums]
  exact Bucket.sum_holds _ (artBuckets_hold _)

theorem illustration_totals_hold : Data.Illustration.published.totals.toBucket.Holds := by
  rw [illustration_totals_are_row_sums]
  exact Bucket.sum_holds _ (bookBuckets_hold _ _)

theorem cashbook_totals_hold : Data.CashBook.published.totals.toBucket.Holds := by
  rw [cashbook_totals_are_row_sums]
  exact Bucket.sum_holds _ (bookBuckets_hold _ _)

/-! ## 2. The dealer's third

Stated for every price, not for the data, in `Hopper.Money`:
`thirdToCent_under`, `thirdToCent_within_two_cents`, `roundCent_idempotent`,
`rounded_writing_agrees`, `truncated_third_agrees`,
`net_after_truncated_third_agrees`, `third_of_a_dollar_disagrees`; and for
every rate sixty divides, `CheckedRow.commission_exact`. -/

/-! ## 3. The rows that can be checked -/

theorem checked_count : Data.Checked.rows.length = Data.Checked.claimedCheckable := by
  decide +kernel

theorem checked_rates_exact : Data.Checked.rows.all CheckedRow.rateExact = true := by
  decide +kernel

/-- As many rows agree, within two cents, as the reader says. -/
theorem checked_agree :
    (Data.Checked.rows.filter CheckedRow.agrees).length = Data.Checked.claimedAgree := by
  decide +kernel

/-- And the ones that do not are the ones the reader names, in its order. -/
theorem checked_disagreements :
    (Data.Checked.rows.filter (fun r => !r.agrees)).map (·.ref) =
      Data.Checked.claimedDisagreeRefs := by
  decide +kernel

/-- Row by row, Lean's verdict is the reader's. -/
theorem checked_same_verdict :
    Data.Checked.rows.all (fun r => r.agrees == r.readerAgrees) = true := by
  decide +kernel

/-! ## 4. The pencil sums -/

/-- For every year total Book IV writes that is declared in
`lean/pencil-sums.json`, the reader's receipts for that year come to the
written total plus exactly what the book is declared to leave out — to the
cent, and each thing left out is one of the year's receipts. -/
theorem pencil_sums_reconcile :
    Data.PencilSums.years.all PencilYear.reconciles = true := by
  decide +kernel

end Hopper.Certificate
