#!/usr/bin/env node
/**
 * Writes the data the Lean certificates check (issues #26 and #27).
 *
 * `lean/Hopper/Certificate.lean` proves that what `src/content/accounts.json`
 * publishes about money follows from its own rows: the three buckets, the
 * reader's rounding, the ninety-five rows where a price, a rate and a written
 * figure stand together, and the year totals Book IV writes for itself. This
 * script puts those rows and those published figures into Lean, and does
 * nothing else.
 *
 * ## What it refuses to do
 *
 * It decides no verdict. Whether a row agrees, whether a year's figures are the
 * sum of its rows, whether a total closes, is computed in Lean and nowhere
 * here, so a certificate that passes has not been pre-filtered by the program
 * that wrote its input. What this script does refuse, loudly, is a figure it
 * cannot put into Lean exactly: money that is not a whole number of cents (or,
 * for a written figure, of sixtieths of a cent), a rate whose denominator sixty
 * does not divide, an exact net that falls on a half cent, a duplicate it
 * cannot find, a count that is not the reader's own, or a pencil total that is
 * not on the sheet the declaration names.
 *
 * ## Why every figure is an integer
 *
 * The leaves write dollars and cents, and take commissions of a third, a
 * quarter, a tenth and fifteen per cent. Sixty is divisible by 3, 4, 10 and 20,
 * so in sixtieths of a cent every one of them is whole, including « 33 2/3 ».
 * The rows' nets and the published figures are already rounded to the cent by
 * the reader, and go in as cents.
 *
 *   npm run lean            # writes lean/Hopper/Data/*.lean
 *   cd lean && lake build   # proves them
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const accounts = JSON.parse(readFileSync(resolve(root, 'src/content/accounts.json'), 'utf8'));
const declared = JSON.parse(readFileSync(resolve(root, 'lean/pencil-sums.json'), 'utf8'));
const outDir = resolve(root, 'lean/Hopper/Data');
mkdirSync(outDir, { recursive: true });

const fail = (msg) => {
  console.error(`lean: ${msg}`);
  process.exit(1);
};

/* --------------------------------------------------------------- exact units */

const whole = (x, scale, what) => {
  const v = x * scale;
  const n = Math.round(v);
  if (Math.abs(v - n) > 1e-4) fail(`${what}: ${x} is not a whole number of 1/${scale} dollars`);
  return n;
};
const cents = (x, what) => whole(x, 100, what);
const sixtieths = (x, what) => whole(x, 6000, what);

const gcd = (a, b) => (b ? gcd(b, a % b) : a);
const rate = (written, what) => {
  let m = /^1\/(\d+)$/.exec(written ?? '');
  let num;
  let den;
  if (m) [num, den] = [1, Number(m[1])];
  else if ((m = /^(\d+)%$/.exec(written ?? ''))) {
    const g = gcd(Number(m[1]), 100);
    [num, den] = [Number(m[1]) / g, 100 / g];
  } else fail(`${what}: rate « ${written} » is neither 1/n nor n%`);
  if (60 % den !== 0) fail(`${what}: rate ${written} has a denominator sixty does not divide`);
  return { num, den };
};

const where = (e) => `${e.ledger} leaf ${e.leaf} (ref ${e.ref})`;
const str = (s) => `"${String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;

/** A list literal, cut into definitions of at most 250 items so the elaborator's recursion depth is never the limit. */
const list = (name, type, items) => {
  const chunks = [];
  for (let i = 0; i < items.length; i += 250) chunks.push(items.slice(i, i + 250));
  if (!chunks.length) return `def ${name} : List ${type} := []\n`;
  const parts = chunks.map(
    (c, k) => `def ${name}${k} : List ${type} := [\n${c.map((x) => `  ${x}`).join(',\n')}\n]\n`,
  );
  return parts.join('\n') + `\ndef ${name} : List ${type} :=\n  ${chunks.map((_, k) => `${name}${k}`).join(' ++ ')}\n`;
};

const header = (what) =>
  `import Hopper.Accounts\n\n/-!\n${what}\n\nGenerated by \`scripts/lean.mjs\` from \`src/content/accounts.json\` (generated ${accounts.generated})` +
  ` and \`lean/pencil-sums.json\`. Do not edit: run \`npm run lean\`.\n-/\n\n`;

/* ------------------------------------------------------- the checked rows */

const checked = accounts.entries.filter((e) => e.check !== null && e.check !== undefined);
const checkedRows = checked.map((e) => {
  if (e.written === null || e.written === undefined) fail(`${where(e)}: a checked row with no written figure`);
  const { num, den } = rate(e.rateWritten, where(e));
  return (
    `⟨${str(e.ledger)}, ${str(e.leaf)}, ${Number(e.ref)}, ${cents(e.gross, where(e))}, ${num}, ${den}, ` +
    `${sixtieths(e.written, where(e))}, ${e.check === 'agrees'}⟩`
  );
});
const disagreeRefs = checked.filter((e) => e.check === 'disagrees').map((e) => Number(e.ref));

writeFileSync(
  resolve(outDir, 'Checked.lean'),
  header('# The rows where a price, a rate and a written figure stand together') +
    `namespace Hopper.Data.Checked\nopen Hopper\n\n` +
    `/-- The reader's own counts, from \`arithmetic\`. -/\n` +
    `def claimedCheckable : Nat := ${accounts.arithmetic.checkable}\n` +
    `def claimedAgree : Nat := ${accounts.arithmetic.agree}\n` +
    `def claimedDisagreeRefs : List Nat := [${disagreeRefs.join(', ')}]\n\n` +
    list('rows', 'CheckedRow', checkedRows) +
    `\nend Hopper.Data.Checked\n`,
);

/* -------------------------------------------------------- the activities */

const activity = (key) => accounts.activities.find((a) => a.key === key) ?? fail(`no activity ${key}`);

const published = (a) => {
  const years = a.years.map(
    (y) =>
      `⟨${y.year}, ${cents(y.accrued, `${a.key} ${y.year}`)}, ${cents(y.received, `${a.key} ${y.year}`)}, ` +
      `${cents(y.notRecorded, `${a.key} ${y.year}`)}, ${cents(y.outstanding, `${a.key} ${y.year}`)}⟩`,
  );
  const t = a.totals;
  return (
    list('publishedYears', 'YearFigures', years) +
    `\ndef published : Published :=\n  ⟨${a.rows}, publishedYears, ⟨${cents(t.accrued, 'total')}, ${cents(t.collected, 'total')}, ` +
    `${cents(t.outstanding, 'total')}, ${cents(t.notRecorded, 'total')}⟩⟩\n`
  );
};

// The work books, counted once across volumes: the reader collapses a sale
// written into two volumes before any total, and publishes which one it dropped.
if (accounts.duplicates.count !== accounts.duplicates.sample.length)
  fail('duplicates.sample is not the whole list, so the collapse cannot be replayed');
let art = accounts.entries.filter((e) => e.activity === 'art');
for (const d of accounts.duplicates.sample) {
  const hit = art.filter(
    (e) => e.ledger === d.dropped.ledger && e.leaf === d.dropped.leaf && e.ref === d.dropped.ref && e.year === d.dropped.year,
  );
  if (hit.length !== 1) fail(`duplicate ${d.work}: ${hit.length} rows match the dropped one`);
  art = art.filter((e) => e !== hit[0]);
}
const artRows = art.map((e) => {
  const { num, den } = rate(e.rateWritten, where(e));
  const g = cents(e.gross, where(e));
  const exact = g * 60 - g * num * (60 / den);
  if (((exact % 60) + 60) % 60 === 30) fail(`${where(e)}: the exact net falls on a half cent`);
  const ry = e.receiptYear === null ? 'none' : `some ${e.receiptYear}`;
  return `⟨${e.year}, ${ry}, ${g}, ${num}, ${den}, ${cents(e.net, where(e))}⟩`;
});

const book = (key) => {
  const charges = accounts.entries
    .filter((e) => e.activity === key && !e.instalmentOf)
    .map((e) => `⟨${e.year}, ${cents(e.net, where(e))}⟩`);
  const receipts = accounts.receipts
    .filter((r) => r.activity === key)
    .map((r) => `⟨${r.year}, ${cents(r.amount, where(r))}⟩`);
  return list('charges', 'Charge', charges) + '\n' + list('receipts', 'Receipt', receipts);
};

writeFileSync(
  resolve(outDir, 'Activities.lean'),
  header('# The three activities: the rows, and the figures the reader publishes from them') +
    `namespace Hopper.Data.Art\nopen Hopper\n\n` +
    list('rows', 'ArtRow', artRows) +
    '\n' +
    published(activity('art')) +
    `\nend Hopper.Data.Art\n\n` +
    `namespace Hopper.Data.Illustration\nopen Hopper\n\n` +
    book('illustration') +
    '\n' +
    published(activity('illustration')) +
    `\nend Hopper.Data.Illustration\n\n` +
    `namespace Hopper.Data.CashBook\nopen Hopper\n\n` +
    book('cashbook') +
    '\n' +
    published(activity('cashbook')) +
    `\nend Hopper.Data.CashBook\n`,
);

/* -------------------------------------------------------- the pencil sums */

const sheetText = (batch, ref) => {
  const tex = readFileSync(
    resolve(root, `transcripts/book-iv/batch-${String(batch).padStart(2, '0')}.tex`),
    'utf8',
  );
  const at = tex.indexOf(`\\sheet{${ref}}`);
  if (at < 0) fail(`batch ${batch} has no sheet ${ref}`);
  const next = tex.indexOf('\\sheet{', at + 1);
  return tex.slice(at, next < 0 ? undefined : next);
};

const pencilYears = declared.totals.map((t) => {
  const what = `pencil total ${t.year} on leaf ${t.leaf}`;
  if (!sheetText(t.batch, t.ref).includes(t.match)) fail(`${what}: « ${t.match} » is not on sheet ${t.ref}`);
  const receipts = accounts.receipts.filter((r) => r.ledger === 'book-iv' && r.year === t.year);
  const cheques = receipts.map((r) => `⟨${Number(r.ref)}, ${cents(r.amount, where(r))}⟩`);
  const omits = t.omits.map((o) => {
    const amount = cents(Number(o.amount), `${what}, omitted ${o.amount}`);
    if (!receipts.some((r) => Number(r.ref) === o.ref && cents(r.amount, where(r)) === amount))
      fail(`${what}: the declared omission ${o.amount} on ref ${o.ref} is not one of the year's receipts`);
    return `⟨${o.ref}, ${amount}⟩`;
  });
  return (
    `⟨${t.year}, ${str(t.leaf)}, ${t.ref}, ${cents(Number(t.written), what)},\n` +
    `    [${cheques.join(', ')}],\n    [${omits.join(', ')}]⟩`
  );
});

writeFileSync(
  resolve(outDir, 'PencilSums.lean'),
  header('# The year totals Book IV writes for itself, and the receipts under them') +
    `namespace Hopper.Data.PencilSums\nopen Hopper\n\n` +
    list('years', 'PencilYear', pencilYears) +
    `\nend Hopper.Data.PencilSums\n`,
);

console.log(
  `lean: ${checkedRows.length} checked row(s), ${artRows.length} work-book row(s), ` +
    `${pencilYears.length} pencil total(s) written to lean/Hopper/Data/`,
);

/* ------------------------------------------------- Book IV's reader (#27) */

// Every Book IV row as the reader saw it and what it decided, written by
// `npm run accounts`. The model in lean/Hopper/BookIV.lean decides every row
// again from the same cells and words, and the certificate proves the two
// agree row by row.
const ivRows = JSON.parse(readFileSync(resolve(root, 'lean/book-iv-rows.json'), 'utf8')).rows;
const BITS = [
  'working', 'money', 'struck', 'rubbed', 'ruled', 'inkRed', 'inkPencil', 'dateEmpty',
  'bodyEmpty', 'bodyDashes', 'bodyIsYear', 'wReceipt', 'wDittoTailed', 'wBill', 'wDeduction',
  'wPaidOnAcct', 'wCarry', 'wDitto', 'wDittoHeadedOrAnd', 'wLetters', 'wExpenses', 'wRestated',
  'wNetCheck', 'wYearTotal', 'wTotalOnly',
];
const KINDS = new Set(['receipt', 'bill', 'deduction', 'carry', 'item', 'bare', 'pencil']);
const DISPS = new Set([
  'yearLine', 'struck', 'text', 'rubbedDraft', 'unread', 'pencilSum', 'receipt', 'rubbedReceipt',
  'deduction', 'carriedForward', 'netRestated', 'subtotal', 'carriedSum', 'billRestating',
  'wordlessReceipt', 'chargeItem', 'chargeBare', 'chargeBill', 'instalment',
]);
const keyIds = new Map();
const opt = (v) => (v === undefined || v === null ? 'none' : `(some ${v})`);
const bits = (names, t) => names.reduce((n, name, i) => n + (t[name] ? 2 ** i : 0), 0);
const ivRaw = ivRows.map((t, i) => {
  const what = `Book IV row ${i} (ref ${t.ref})`;
  const inks = { ...t, inkRed: t.ink === 'red', inkPencil: t.ink === 'pencil' };
  if (t.kind !== undefined && !KINDS.has(t.kind)) fail(`${what}: kind « ${t.kind} » is not one the model knows`);
  if (!DISPS.has(t.disp)) fail(`${what}: disposition « ${t.disp} » is not one the model knows`);
  if (t.read !== undefined && !Number.isInteger(t.read)) fail(`${what}: figure ${t.read} is not in cents`);
  let key = 'none';
  if (t.key) {
    if (!keyIds.has(t.key)) keyIds.set(t.key, keyIds.size);
    key = `(some ${keyIds.get(t.key)})`;
  }
  const body = bits(['titled', 'fEmpty', 'fRestated', 'fPaidOnAcct', 'fNetCheck', 'fYearTotal'], t);
  return (
    `⟨${t.batch}, ${Number(t.ref)}, ${opt(t.pencil)}, ${opt(t.read)}, ${opt(t.dateYear)}, ${opt(t.bodyYear)}, ` +
    `${bits(BITS, inks)}, ${t.kind ? `(some .${t.kind})` : 'none'}, ${opt(t.year)}, ${body}, .${t.disp}, ` +
    `${key}, ${bits(['instWords', 'payWords'], t)}⟩`
  );
});
const ill = accounts.illustration;
writeFileSync(
  resolve(outDir, 'BookIV.lean'),
  header("# Book IV's rows, as the reader saw them and what it decided").replace(
    'import Hopper.Accounts',
    'import Hopper.BookIVRaw',
  ) +
    `namespace Hopper.Data.BookIV\nopen Hopper.BookIV\n\n` +
    `/-- The reader's own counters, from \`illustration\` in accounts.json. -/\n` +
    `def claimed : Claims := ⟨${ill.charges}, ${ill.receipts}, ${ill.subtotalsExcluded}, ` +
    `${ill.deductionsExcluded}, ${ill.netsExcluded}, ${ill.carriedSumsExcluded}, ${ill.struckExcluded}, ` +
    `${ill.wordlessReceipts}, ${ill.rubbedExcluded}, ${ill.pencilSumsExcluded}, ${ill.instalmentsCollapsed}⟩\n\n` +
    list('raw', 'Raw', ivRaw) +
    `\nend Hopper.Data.BookIV\n`,
);
console.log(`lean: ${ivRaw.length} Book IV row(s), ${keyIds.size} picture title(s)`);
