import Hopper.Accounts

/-!
# The year totals Book IV writes for itself, and the receipts under them

Generated by `scripts/lean.mjs` from `src/content/accounts.json` (generated 2026-09-19T20:23:41.280Z) and `lean/pencil-sums.json`. Do not edit: run `npm run lean`.
-/

namespace Hopper.Data.PencilSums
open Hopper

def years0 : List PencilYear := [
  ⟨1946, "120", 16926, 534157,
    [⟨16926, 299440⟩, ⟨16926, 234717⟩],
    []⟩,
  ⟨1947, "121", 16778, 236053,
    [⟨16926, 180000⟩, ⟨16778, 4053⟩, ⟨16778, 50000⟩, ⟨16778, 2000⟩],
    []⟩,
  ⟨1949, "124", 17734, 366114,
    [⟨17079, 566⟩, ⟨17248, 10000⟩, ⟨17248, 166667⟩, ⟨17734, 178881⟩, ⟨17734, 10000⟩],
    []⟩,
  ⟨1951, "127", 17181, 487000,
    [⟨17173, 35000⟩, ⟨17181, 350000⟩, ⟨17181, 1000⟩, ⟨17181, 1000⟩, ⟨17181, 100000⟩],
    []⟩,
  ⟨1961, "150", 17889, 1563721,
    [⟨17149, 500000⟩, ⟨17149, 1720⟩, ⟨17238, 23667⟩, ⟨17238, 5000⟩, ⟨17889, 1033334⟩],
    []⟩,
  ⟨1962, "152", 17664, 3984256,
    [⟨17889, 563393⟩, ⟨18073, 863⟩, ⟨18073, 333334⟩, ⟨18073, 350000⟩, ⟨18073, 1000000⟩, ⟨17664, 1736666⟩, ⟨16161, 37500⟩],
    [⟨16161, 37500⟩]⟩
]

def years : List PencilYear :=
  years0

end Hopper.Data.PencilSums
